schema_version: 1

context:
  version: 1.8.1

package:
  name: livekit-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/livekit-agents/livekit_agents-${{ version }}.tar.gz
    sha256: 9319b4a7cf3891db4c1de9edd98fad4918919beadb2ceff5b3fbd34ae67384b5
  - url: https://raw.githubusercontent.com/livekit/agents/refs/tags/livekit-agents%40${{ version }}/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    file_name: LICENSE

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - certifi >=2025.6.15
    - livekit ==1.1.18
    - livekit-api >=1.2.0,<2
    - livekit-protocol >=1.1.21,<2
    - livekit-blingfire >=1.1,<2.dev0,<2
    - protobuf >=3
    - pyjwt >=2.0
    - types-protobuf >=4
    - psutil >=7.0
    - aiohttp >=3.10,<4.dev0
    - typing_extensions >=4.12
    - docstring_parser >=0.16
    - eval-type-backport
    - colorama >=0.4.6
    - av >=14.0.0
    - numpy >=1.26.0
    - pydantic >=2.5,<3
    - nest-asyncio >=1.6.0
    - opentelemetry-api >=1.39.0,<1.45
    - opentelemetry-sdk >=1.39.0,<1.45
    - opentelemetry-exporter-otlp >=1.39.0,<1.45
    - prometheus_client >=0.22
    - openai >=2,<3
    - aiofiles >=24
    - json-repair ==0.60.1
    - pyyaml >=6.0.3
    - typer >=0.15.1
    - click >=8.1,<9.dev0
    - python-sounddevice >=0.5
    - watchfiles >=1.0
    - livekit-local-inference >=0.2.7
tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - livekit.agents
      pip_check: true

about:
  summary: A powerful framework for building realtime voice AI agents
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/livekit-agents/
  repository: https://github.com/livekit/agents
  documentation: https://docs.livekit.io

extra:
  recipe-maintainers:
    - conda-forge/livekit
